### ISSUE TITLE
大佬，表格同步刷新时的问题

### ISSUE THREAD

**Issue by huoxuxu** [w0624/jquery-pagination#2]
大佬，
能不能做一个表格同步刷新的分页demo，我试了，貌似有问题的。。。
ajax是可以的
怎么下拉框里有8个 undefined

**Comment by w0624** [comment]
一开始做这个分页插件就是要独立出来，不带表格的，如果要带表格，一般是后台应用，而且是有现成的框架，另外一点，考虑的是前后端分离，所以适合ajax结合使用，下拉框里有undefined，可能是配置不对，如果是数字类型，不要用字符串形式去表示，不知道我的回答有没有帮到你？

**Comment by w0624** [comment]
> 大佬，
> 能不能做一个表格同步刷新的分页演示，我试了，貌似有问题的... 
> ajax是可以的
> 怎么下拉框里有8个undefined

一开始做这个分页插件就是要独立出来，不带表格的，如果要带表格，一般是后台应用，而且是有现成的框架，另外一点，考虑的是前后端分离，所以适合AJAX结合使用，下拉框里有不确定的，可能是配置不对，如果是数字类型，不要用字符串形式去表示，不知道我的回答有没有帮到你？

**Comment by w0624** [comment]
> 大佬，
> 能不能做一个表格同步刷新的分页演示，我试了，貌似有问题的... 
> ajax是可以的
> 怎么下拉框里有8个undefined

一开始做这个分页插件就是要独立出来，不带表格的，如果要带表格，一般是后台应用，而且是有现成的框架，另外一点，考虑的是前后端分离，所以适合AJAX结合使用，下拉框里有undefined，可能是配置不对，如果是数字类型，不要用字符串形式去表示，不知道我的回答有没有帮到你？

**Comment by huoxuxu** [comment]
非ajax  其实分页控件只需要暴露一个可以根据pageIndex 定位到指定页码的方法即可

**Comment by w0624** [comment]
> 非ajax 其实分页控件只需要暴露一个可以根据pageIndex 定位到指定页码的方法即可

你这么说我了解，不过可以先初始化插件，总页数为0或者不填这个属性，然后在用 setPage 方法重新渲染即可，只是多了一步操作，或者你可以改插件里的代码，加入当前页定位也是可以的。

**Comment by huoxuxu** [comment]
好的，我试一下
